application: zywien-web
version: 1
runtime: python27
api_version: 1
threadsafe: false
default_expiration: "2d"

skip_files:
  - ^node_modules$
  - ^(.*/)?\.js.map$
  - ^(.*/)?\.scss$
  - ^(.*/)?.*/app/.js*$
  - ^(.*/)?.*/node_modules/.*$
  - ^(node_modules/.*)

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  secure: always
  upload: favicon\.ico
- url: /dist
  static_dir: dist
  secure: always
- url: /img
  static_dir: static/images
  secure: always
- url: /theme
  static_dir: static/styles
  secure: always
- url: /.*
  script: server.main.application
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

